/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSlidesRouteImport } from './routes/_authenticated/admin/slides'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminOfertasRouteImport } from './routes/_authenticated/admin/ofertas'
import { Route as AuthenticatedAdminExtratoRouteImport } from './routes/_authenticated/admin/extrato'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminConfiguracoesWhatsappRouteImport } from './routes/_authenticated/admin/configuracoes-whatsapp'
import { Route as AuthenticatedAdminConfiguracoesLojaRouteImport } from './routes/_authenticated/admin/configuracoes-loja'
import { Route as AuthenticatedAdminConfiguracoesEnvioRouteImport } from './routes/_authenticated/admin/configuracoes-envio'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as ApiPublicCronCleanupPedidosPdfRouteImport } from './routes/api/public/cron/cleanup-pedidos-pdf'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSlidesRoute =
  AuthenticatedAdminSlidesRouteImport.update({
    id: '/slides',
    path: '/slides',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOfertasRoute =
  AuthenticatedAdminOfertasRouteImport.update({
    id: '/ofertas',
    path: '/ofertas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExtratoRoute =
  AuthenticatedAdminExtratoRouteImport.update({
    id: '/extrato',
    path: '/extrato',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesWhatsappRoute =
  AuthenticatedAdminConfiguracoesWhatsappRouteImport.update({
    id: '/configuracoes-whatsapp',
    path: '/configuracoes-whatsapp',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesLojaRoute =
  AuthenticatedAdminConfiguracoesLojaRouteImport.update({
    id: '/configuracoes-loja',
    path: '/configuracoes-loja',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesEnvioRoute =
  AuthenticatedAdminConfiguracoesEnvioRouteImport.update({
    id: '/configuracoes-envio',
    path: '/configuracoes-envio',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicCronCleanupPedidosPdfRoute =
  ApiPublicCronCleanupPedidosPdfRouteImport.update({
    id: '/api/public/cron/cleanup-pedidos-pdf',
    path: '/api/public/cron/cleanup-pedidos-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes-envio': typeof AuthenticatedAdminConfiguracoesEnvioRoute
  '/admin/configuracoes-loja': typeof AuthenticatedAdminConfiguracoesLojaRoute
  '/admin/configuracoes-whatsapp': typeof AuthenticatedAdminConfiguracoesWhatsappRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/extrato': typeof AuthenticatedAdminExtratoRoute
  '/admin/ofertas': typeof AuthenticatedAdminOfertasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/slides': typeof AuthenticatedAdminSlidesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/cron/cleanup-pedidos-pdf': typeof ApiPublicCronCleanupPedidosPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes-envio': typeof AuthenticatedAdminConfiguracoesEnvioRoute
  '/admin/configuracoes-loja': typeof AuthenticatedAdminConfiguracoesLojaRoute
  '/admin/configuracoes-whatsapp': typeof AuthenticatedAdminConfiguracoesWhatsappRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/extrato': typeof AuthenticatedAdminExtratoRoute
  '/admin/ofertas': typeof AuthenticatedAdminOfertasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/slides': typeof AuthenticatedAdminSlidesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/cron/cleanup-pedidos-pdf': typeof ApiPublicCronCleanupPedidosPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes-envio': typeof AuthenticatedAdminConfiguracoesEnvioRoute
  '/_authenticated/admin/configuracoes-loja': typeof AuthenticatedAdminConfiguracoesLojaRoute
  '/_authenticated/admin/configuracoes-whatsapp': typeof AuthenticatedAdminConfiguracoesWhatsappRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/extrato': typeof AuthenticatedAdminExtratoRoute
  '/_authenticated/admin/ofertas': typeof AuthenticatedAdminOfertasRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/slides': typeof AuthenticatedAdminSlidesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/cron/cleanup-pedidos-pdf': typeof ApiPublicCronCleanupPedidosPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes-envio'
    | '/admin/configuracoes-loja'
    | '/admin/configuracoes-whatsapp'
    | '/admin/dashboard'
    | '/admin/extrato'
    | '/admin/ofertas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/slides'
    | '/admin/'
    | '/api/public/cron/cleanup-pedidos-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes-envio'
    | '/admin/configuracoes-loja'
    | '/admin/configuracoes-whatsapp'
    | '/admin/dashboard'
    | '/admin/extrato'
    | '/admin/ofertas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/slides'
    | '/admin'
    | '/api/public/cron/cleanup-pedidos-pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes-envio'
    | '/_authenticated/admin/configuracoes-loja'
    | '/_authenticated/admin/configuracoes-whatsapp'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/extrato'
    | '/_authenticated/admin/ofertas'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/slides'
    | '/_authenticated/admin/'
    | '/api/public/cron/cleanup-pedidos-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronCleanupPedidosPdfRoute: typeof ApiPublicCronCleanupPedidosPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/slides': {
      id: '/_authenticated/admin/slides'
      path: '/slides'
      fullPath: '/admin/slides'
      preLoaderRoute: typeof AuthenticatedAdminSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ofertas': {
      id: '/_authenticated/admin/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AuthenticatedAdminOfertasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/extrato': {
      id: '/_authenticated/admin/extrato'
      path: '/extrato'
      fullPath: '/admin/extrato'
      preLoaderRoute: typeof AuthenticatedAdminExtratoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes-whatsapp': {
      id: '/_authenticated/admin/configuracoes-whatsapp'
      path: '/configuracoes-whatsapp'
      fullPath: '/admin/configuracoes-whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes-loja': {
      id: '/_authenticated/admin/configuracoes-loja'
      path: '/configuracoes-loja'
      fullPath: '/admin/configuracoes-loja'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes-envio': {
      id: '/_authenticated/admin/configuracoes-envio'
      path: '/configuracoes-envio'
      fullPath: '/admin/configuracoes-envio'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesEnvioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/cron/cleanup-pedidos-pdf': {
      id: '/api/public/cron/cleanup-pedidos-pdf'
      path: '/api/public/cron/cleanup-pedidos-pdf'
      fullPath: '/api/public/cron/cleanup-pedidos-pdf'
      preLoaderRoute: typeof ApiPublicCronCleanupPedidosPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesEnvioRoute: typeof AuthenticatedAdminConfiguracoesEnvioRoute
  AuthenticatedAdminConfiguracoesLojaRoute: typeof AuthenticatedAdminConfiguracoesLojaRoute
  AuthenticatedAdminConfiguracoesWhatsappRoute: typeof AuthenticatedAdminConfiguracoesWhatsappRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminExtratoRoute: typeof AuthenticatedAdminExtratoRoute
  AuthenticatedAdminOfertasRoute: typeof AuthenticatedAdminOfertasRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminSlidesRoute: typeof AuthenticatedAdminSlidesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
    AuthenticatedAdminConfiguracoesEnvioRoute:
      AuthenticatedAdminConfiguracoesEnvioRoute,
    AuthenticatedAdminConfiguracoesLojaRoute:
      AuthenticatedAdminConfiguracoesLojaRoute,
    AuthenticatedAdminConfiguracoesWhatsappRoute:
      AuthenticatedAdminConfiguracoesWhatsappRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminExtratoRoute: AuthenticatedAdminExtratoRoute,
    AuthenticatedAdminOfertasRoute: AuthenticatedAdminOfertasRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
    AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
    AuthenticatedAdminSlidesRoute: AuthenticatedAdminSlidesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronCleanupPedidosPdfRoute: ApiPublicCronCleanupPedidosPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
